### ISSUE TITLE
Cannot register package.

### ISSUE THREAD

**Issue by jonasws** [atom/apm#393]
I have been trying for a while to publish my package [github-utils](https://github.com/jonasws/github-utils), but I keep getting the following error when I try to run `apm publish minor` 
```
Registering package in jonasws/github-utils repository failed: 
That repo does not exist, isn't an atom package, or you do not have access
```

I do indeed have access to the repo. I have tried to do `apm login`. Is something at fault with my Atom.io account user? Any comments would be greatly appreciated!

**Comment by izuzak** [comment]
Sorry to hear you're having trouble, @jonasws. 

> I have tried to do apm login. 

What does this mean? Have you tried and succeeded or tried and failed? Could you provide the full output of all apm commands you ran (including the commands themselves), and the contents of your local package.json?

**Comment by jonasws** [comment]
It does indeed look as if I've succeeded in authenticating with `apm login`. (I also opened up the `node`console in the `apm` build directory in order toverify that the `keytar.findPassword` call returned the correct token).

The commands are posted below:
```
jonasws@jonasmacbook:~/github/github-utils (develop) $ apm login
Welcome to Atom!

Before you can publish packages, you'll need an API token.

Visit your account page on Atom.io https://atom.io/account,
copy the token and paste it below when prompted.

Press [Enter] to open your account page on Atom.io. 
Token> _kVhsif7rJg1GWUnxiJ9SJw
Saving token to Keychain ✓
jonasws@jonasmacbook:~/github/github-utils (develop) $ apm publish minor
Registering github-utils ✗
Registering package in jonasws/github-utils repository failed: That repo does not exist, isn't an atom package, or you do not have access
```

The contents of my `package.json` may be found  [here](https://github.com/jonasws/github-utils/blob/develop/package.json)

**Comment by thomasjo** [comment]
Wait, you haven't got a `master` branch? I'm reasonably sure that's an assumed requirement of `apm`.
Try pushing a new branch called `master`;
``` bash
$ git checkout -b master
$ git push -u origin master
$ apm publish minor
```

**Comment by thomasjo** [comment]
Hmm, it looks like my assumption might have been wrong:
https://github.com/atom/apm/blob/master/src/publish.coffee#L247-L248

@thedaniel Any clue?

**Comment by jonasws** [comment]
@thomasjo You were right! I had a develop branch, and when I pushed the same commit to master on my repository, everything went smoothly! Totally went by me that it needed a master branch. I'll take a look through the docs to see where I missed it, but I suspect it may not be that clear, and maybe it should be added to the FAQ or similar somewhere? Could save others a lot of time.

**Comment by thomasjo** [comment]
@jonasws Great news! Still not sure where things are going wrong, but it might be an issue with the package API. Hopefully @thedaniel can shed some light on this.

**Comment by izuzak** [comment]
Great investigation work @thomasjo and @jonasws :mag: -- yeah, I believe there's a dependency on the default branch being called "master" currently (in the atom.io registry code). Opened an internal issue to see what we can do about that. :tophat:

**Comment by jonasws** [comment]
@izzuk Maybe use the GitHub API to check what the default branch is of the given repository when one tries to do `apm publish` without specifying a tag?

**Comment by izuzak** [comment]
@jonasws Yeah, the atom.io registry uses the GitHub API extensively already -- I think specific situation this was an oversight (and the `default_branch` from the API response should be used, as you mentioned), but I'll let the folks maintaining atom.io make the call.

**Comment by jonasws** [comment]
Yeah I figured it would not be an issue to implment that if the current OAuth scope includes those permissions. The option is to state it more explicitly in the docs on creatin packages.

**Comment by thedaniel** [comment]
This issue was moved to atom/atom.io#6
